version: '3.8'

services:
  db:
    build: .
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
